USE [master]
GO

/****** Object:  Database [TelecomService]    Script Date: 15.07.2023 15:18:20 ******/
CREATE DATABASE [TelecomService]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TelecomService', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TelecomService.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TelecomService_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TelecomService_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TelecomService].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TelecomService] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TelecomService] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TelecomService] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TelecomService] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TelecomService] SET ARITHABORT OFF 
GO

ALTER DATABASE [TelecomService] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TelecomService] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TelecomService] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TelecomService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TelecomService] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TelecomService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TelecomService] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TelecomService] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TelecomService] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TelecomService] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TelecomService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TelecomService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TelecomService] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TelecomService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TelecomService] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TelecomService] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TelecomService] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TelecomService] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TelecomService] SET  MULTI_USER 
GO

ALTER DATABASE [TelecomService] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TelecomService] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TelecomService] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TelecomService] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TelecomService] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TelecomService] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TelecomService] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TelecomService] SET  READ_WRITE 
GO

USE [TelecomService]
GO

/****** Object:  Table [dbo].[Clients]    Script Date: 15.07.2023 15:20:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Clients](
	[Id] [int] NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[Phone] [varchar](30) NOT NULL,
	[Email] [varchar](200) NOT NULL,
	[Password] [varchar](200) NOT NULL,
	[Role] [varchar](10) NULL,
 CONSTRAINT [clients_pkey] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [unique_email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [unique_password] UNIQUE NONCLUSTERED 
(
	[Password] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [TelecomService]
GO

/****** Object:  Table [dbo].[Orders]    Script Date: 15.07.2023 15:21:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Orders](
	[Id] [int] NOT NULL,
	[ClientId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[Pr_count] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[Status] [varchar](20) NOT NULL,
	[Address] [varchar](100) NULL,
 CONSTRAINT [orders_pkey] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([ClientId])
REFERENCES [dbo].[Clients] ([Id])
GO

ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([Id])
GO

ALTER TABLE [dbo].[Orders]  WITH CHECK ADD CHECK  (([pr_count]>(0)))
GO

ALTER TABLE [dbo].[Orders]  WITH CHECK ADD CHECK  (([Status]='delivery' OR [Status]='in progress' OR [Status]='done'))
GO

USE [TelecomService]
GO

/****** Object:  Table [dbo].[Products]    Script Date: 15.07.2023 15:22:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Products](
	[Id] [int] NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[Price] [numeric](18, 0) NOT NULL,
	[In_stock] [int] NULL,
 CONSTRAINT [products_pkey] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Products] ADD  DEFAULT ((0)) FOR [In_stock]
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([in_stock]>=(0)))
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([in_stock]>=(0)))
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([In_stock]>=(0)))
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([price]>(0)))
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([price]>(0)))
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([Price]>(0)))
GO

USE [TelecomService]
GO





